apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube-dp
  namespace: sonarqube
  labels:
    app: sonarqube
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      initContainers:
      - name: init
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
      containers:
      - name: sonarqube-container
        image: sonarqube:8.9.1-community
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9000
        envFrom:
        - configMapRef:
            name: sonarqube-cfg
        volumeMounts:
        - name: sonarqube-pvc
          mountPath: "/opt/sonarqube/data/"
          subPath: data
        - name: sonarqube-pvc
          mountPath: "/opt/sonarqube/extensions/"
          subPath: extensions
      volumes:
      - name: sonarqube-pvc
        persistentVolumeClaim:
          claimName: sonarqube-pvc