apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crud-php-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/luuisavelino/CRUD_PHP-Configuration.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: crud-php
  
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true

    syncOptions:
    - CreateNamespace=true